Ensure semVer compliance

diff --git a/.github/workflows/publish-image.yml b/.github/workflows/publish-image.yml
--- a/.github/workflows/publish-image.yml
+++ b/.github/workflows/publish-image.yml
@@ -27,6 +27,22 @@ jobs:
         with:
           fetch-depth: 0
 
+      # Validate that the Image is published with a tag that is a valid SemVer, required by Helm chart
+      - name: Validate SemVer2 version compliance
+        if: startsWith(github.ref, 'refs/tags/')
+        env:
+          SEMVER_REGEX: ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$
+
+        run: |
+          ref="${{ github.ref_name }}"
+          my_regex="${{env.SEMVER_REGEX}}"
+          if [[ "$ref" =~ $my_regex ]]; then
+            echo "SemVer compliant version: $ref"
+          else
+            echo "Invalid SemVer version: $ref"
+            exit 1
+          fi
+
       - name: Log in to the Container registry
         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
         with:
@@ -48,6 +64,7 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
   build-and-publish-chart:
     runs-on: ubuntu-latest
     needs: build-and-push-image
